<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManager;
/**
 * StripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StripRepository extends \Doctrine\ORM\EntityRepository
{


    public function showAllUsedStrips()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQuery("
          SELECT l, s FROM AppBundle:Strip s
           JOIN s.lid l
           WHERE s.used=TRUE ORDER BY s.usedAt DESC, l.voornaam ASC
        ");
        return $qb->getResult();
    }


}
